version: '3.8'

services:
  db:
    image: postgres:15
    container_name: budget_app_postgres_db
    environment:
      POSTGRES_DB: budgetapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: